server:
  port: 8081

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=KardexSAP;encrypt=true;trustServerCertificate=true
    username: sa
    password: InnovaTech_2026!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate # Solo valida que las tablas creadas por nuestro script existan
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true       # Muestra las consultas SQL reales por consola para fines educativos
    properties:
      hibernate:
        format_sql: true # Formatea de manera legible las consultas SQL en consola
