version: '3.8'

services:
  # 🗄️ Capa de Datos: Base de Datos ERP Core (SQL Server)
  sap-erp-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sap-erp-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=InnovaTech_2026!
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sql:/usr/config
    networks:
      - innovatech-network

  # 🌐 Middleware: Spring Cloud Gateway (API Gateway)
  api-gateway:
    image: openjdk:17-jdk-slim
    container_name: innovatech-gateway
    ports:
      - "80:8080"
    volumes:
      - ../api-gateway:/app
    working_dir: /app
    command: "./mvnw spring-boot:run"
    depends_on:
      - inventory-service
      - sales-orchestrator
    networks:
      - innovatech-network

  # 📦 Entity Service: Microservicio de Inventario
  inventory-service:
    image: openjdk:17-jdk-slim
    container_name: inventory-service
    ports:
      - "8081:8081"
    volumes:
      - ../inventory-service:/app
    working_dir: /app
    command: "./mvnw spring-boot:run"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sap-erp-db:1433;databaseName=KardexSAP;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=InnovaTech_2026!
    depends_on:
      - sap-erp-db
    networks:
      - innovatech-network

  # 🎼 Task Service: Orquestador de Ventas Híbrido
  sales-orchestrator:
    image: openjdk:17-jdk-slim
    container_name: sales-orchestrator
    ports:
      - "8082:8082"
    volumes:
      - ../sales-orchestrator:/app
    working_dir: /app
    command: "./mvnw spring-boot:run"
    networks:
      - innovatech-network

volumes:
  sqlserver_data:

networks:
  innovatech-network:
    driver: bridge
